# Generated by Django 5.0 on 2024-02-21 09:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0003_remove_userdata_email_remove_userdata_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdata',
            new_name='user_data',
        ),
    ]
